### ISSUE TITLE
Product price cannot exceed $10k

### ISSUE THREAD

**Issue by kimberly-bird** [raving-remoras/bangazon-site#24]
**Given** a user wants to sell a product
**When** the user is filling out the product form
**And** enters is a price that is greater than $10,000
**Then** the user should be notified that the price must be $10,000 or less

**Comment by kellymorin** [comment]
Results in an IntegrityError because we set a limit in the model to 10,000. Handle the error and let the user know about the constraint. Issue ticket #61

**Comment by kellymorin** [comment]
Approved and Merged 2/13
